# =========================
# Builder stage
# =========================
FROM rust:1.90-alpine3.20 AS builder

RUN apk add --no-cache build-base musl-dev pkgconf && \
    rustup target add x86_64-unknown-linux-musl

WORKDIR /app

# Cache dependencies
COPY Cargo.toml Cargo.lock ./
RUN mkdir -p src/bin && echo 'fn main() { println!("prebuild binnary"); }' > src/bin/main.rs
RUN cargo build --release --target x86_64-unknown-linux-musl
RUN rm -rf src

